spring:
  application:
    name: order-worker
  threads:
    virtual:
      enabled: true
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/b2b_orders}
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    consumer:
      group-id: order-worker-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.value.default.type: com.mariposa.orderworker.infrastructure.dto.KafkaOrderInputDto
        spring.json.trusted.packages: "*"
        orders-topic: orders-topic
        orders-dlt-topic: orders-dlt
    listener:
      concurrency: 1
  cloud:
    circuitbreaker:
      resilience4j:
        enabled: true
        instances:
          clientsApi:
            circuitbreaker:
              slidingWindowSize: 10
              failureRateThreshold: 50
              waitDurationInOpenState: 10s
              permittedNumberOfCallsInHalfOpenState: 3
            timelimiter:
              timeoutDuration: 6s
          productsApi:
            circuitbreaker:
              slidingWindowSize: 10
              failureRateThreshold: 50
              waitDurationInOpenState: 10s
              permittedNumberOfCallsInHalfOpenState: 3
            timelimiter:
              timeoutDuration: 6s

resilience4j:
  retry:
    instances:
      clientsApi:
        maxAttempts: 3
        waitDuration: 1s
        exponentialBackoff:
          enabled: true
          multiplier: 2
        retryExceptions:
          - java.lang.RuntimeException
          - org.springframework.web.reactive.function.client.WebClientResponseException
          - java.io.IOException
          - java.util.concurrent.TimeoutException
      productsApi:
        maxAttempts: 3
        waitDuration: 1s
        exponentialBackoff:
          enabled: true
          multiplier: 2
        retryExceptions:
          - java.lang.RuntimeException
          - org.springframework.web.reactive.function.client.WebClientResponseException
          - java.io.IOException
          - java.util.concurrent.TimeoutException

app:
  cache:
    ttl-seconds: ${CACHE_TTL_SECONDS:300}
  services:
    products-url: ${PRODUCTS_API_URL:http://localhost:8081}
    clients-url: ${CLIENTS_API_URL:http://localhost:8082}